### PR TITLE
Added missing option to ApexChartOptions

### LINKED ISSUE #532: Blazor binding for the option "allowMouseWheelZoom" is missing
I'm trying to disable the mouse wheel zoom which is now apparently enabled by default. I want to leave the zoom features via the toolbar functioning so I cannot simply disable zoom. Although [not well documented](https://stackoverflow.com/questions/79033169/how-to-disable-scroll-wheel-zoom-in-apexcharts), there is a flag in the Chart.Zoom options called `allowMouseWheelZoom` (see [here](https://github.com/apexcharts/apexcharts.js/blob/81478fba039e9200cb6dcd38bf00684284b2fd74/src/modules/settings/Options.js#L392)) which can be set to false. I can do this via JS Interop but would be better if this option were exposed via the C# bindings.

### PR DESCRIPTION
**Pull request by aharwood2**
Closes #532

### CODE REVIEW

**Review by joadan — CHANGES_REQUESTED** [review]
Please set the property to nullable bool (bool?) and no default value.
We want to have the default values to be set from JavaScript this way we save some bytes being sent.

Thank you!

**Comment by w3ori** [comment]
Welcomed PR, I'm wainting for this.

**Comment by joadan** [comment]
Fixed in #537

**Comment by aharwood2** [comment]
> Welcomed PR, I'm wainting for this.
> 
> I ceated a PR for faster approval: #537 How is it binded to the chart?

You just duplicated my PR, why would that get faster approval? It just makes more admin work for the code owner.

**Pull request closed without merging**
