### PR TITLE
Fixed tooltipHoverFormatter not being deserialized as a function

### LINKED ISSUE #449: [Bug] TooltipHoverFormatter is deserialized as a string, resulting in a "not a function" error when using shared tooltips
When specifying a custom tooltip formatter using `ApexChartOptions<T>.Legend.TooltipHoverFormatter`, the browser throws an exception when the user tries to hover over the area chart, as it tries to call a string like a function. 

The problem comes from `blazor-apexcharts.js` that has [custom logic](https://github.com/apexcharts/Blazor-ApexCharts/blob/master/src/Blazor-ApexCharts/wwwroot/js/blazor-apexcharts.js#L424) for evaluating function-like string parameters coming from .NET, but it doesn't include TooltipHoverFormatter. I think the solution is as simple as adding ` || key === 'tooltipHoverFormatter'` at the end of that if statement.

### PR DESCRIPTION
**Pull request by SparkyTD**
Fixes #449 

I added 'tooltipHoverFormatter' to the list of JSON keys that will be evaluated as a function in the browser.

### CODE REVIEW

**Comment by SparkyTD** [comment]
I think there might be a more flexible way of solving this, using an attribute on the C# side, and some custom serialization/deserialization logic.

I'll look into the feasibility of that solution, and I might create another PR if it looks good.

**Comment by SparkyTD** [comment]
@joadan I have implemented the idea I was referring to: [fucntion-serializer](https://github.com/apexcharts/Blazor-ApexCharts/compare/master...SparkyTD:Blazor-ApexCharts:function-serializer). It basically uses a custom JsonConverter to prefix all function strings with a custom JSON key ('@eval'), and replaces the name checking logic on the JS side with a much simpler logic that checks if a string is prefixed with this key.

So instead of serializing a function as `myFunction: "function(arg) { ... }"`, it gets serialized as such:
```
myFunction: {
    "@eval": "function(arg) { ... }"
}
```

This way the client can simply check if the value is an object containing the '@eval' key, and use that to decide whether or not to evaluate the contents. It also works for function arrays that use `CustomFunction`.

Please tell me if this looks good, and I should open another PR.

**Comment by joadan** [comment]
@SparkyTD, this sounds great!
If you create a PR I'll take a look at it.

Thank you for your work!

**Comment by SparkyTD** [comment]
No problem, I love this project!

I created the PR: https://github.com/apexcharts/Blazor-ApexCharts/pull/453

**Pull request merged**
